version: "3.9"

services:
  web:
    build: .
    container_name: rails
    command: bin/rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0

  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: time_register_development
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  bundle_cache:
  redis_data:
